highlighter: pygments
permalink: /news/:title
baseurl: /europeantestingconference
sass:
    style: :compressed
    sass_dir: styles/_snippets
collections:
- sections
- schedule
- speakers
- volunteers
defaults:
    -
        scope:
            path: "_participants"
        values:
            layout: "sub-page"
    -
        scope:
            path: "2015/participants"
        values:
            layout: "sub-page"
    -
        scope:
            path: "2015"
        values:
            layout: "index"
navigation:
  - title : "Home"
    url   : "/index.html"
  - title : "Schedule"
    url   : "/#schedule"
  - title : "Speakers"
    url   : "/speakers/index.html"
  - title : "Call for speakers"
    url   : "/"